FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    nagios4 \
    nagios-plugins \
    apache2 \
    && a2enmod auth_digest authz_groupfile authz_user auth_basic cgi \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 80 443

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
